version: "3.3"

services:
  db:
    image: db:1.0
    container_name: db
    environment:
        POSTGRES_DB: laravel
        POSTGRES_USER: sysadmin
        POSTGRES_PASSWORD: testing_123
    ports:
        - "5432:5432"
    volumes:
        - data:/var/lib/postgresql/data
    networks:
      - app_network

  app:
    image: suhu-api:1.0
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - db
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - app_network

volumes:
    data:
        driver: local

networks:
    app_network:
        driver: bridge

